version: '3'

services:
  
  rkots:
    build: .
    ports: 
      - '9000:8080'
    env_file:
      - .env
    depends_on:
      - rkots-db

  rkots-db:
    image: postgres:10
    container_name: 'rkots-db'
    ports:
      - 5432:5432
    env_file:
      - .env
  