spring:
  application:
    name: ${APPLICATION_NAME}
  profiles:
    active: ${ACTIVE_PROFILE}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: update
        hbm2ddl.auto: create-drop
        naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    serialization:
      indent_output: true
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver