spring:
  datasource:
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
  
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update

app:
  jwt-secret: ${APP_JWT_SECRET}
  jwt-expiration: ${APP_JWT_EXPIRATION}

iex:
  key: ${IEX_KEY}