server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${APPLICATION_NAME}
  profiles:
    active: ${ACTIVE_PROFILE}

  mvc:
    view:
      prefix: /
      suffix: .jsp

  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
    initialization-mode: always
  
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: create-drop
    show-sql: false
    generate-ddl: true
    
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    time-zone: UTC

app:
  jwt-secret: ${APP_JWT_SECRET}
  jwt-expiration: ${APP_JWT_EXPIRATION}