spring:
  datasource:
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true

app:
  jwt-secret: ${APP_JWT_SECRET}
  jwt-expiration: ${APP_JWT_EXPIRATION}

iex:
  key: ${IEX_KEY}