spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: testdb
    password: shhdhh27sk?
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

app:
  jwt-secret: ${APP_JWT_SECRET}
  jwt-expiration: ${APP_JWT_EXPIRATION}

iex:
  key: ${IEX_KEY}